# numpy practice session

In [ ]:
# pip intsall numpy  to install this numpy library

In [1]:
# import this library in j.notebook
import numpy as np

# Create an array using numpy library

In [3]:
# 1_Dimensional array
food= np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [10]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [11]:
len(price)

3

In [14]:
price[0:]

array([5, 5, 5])

In [15]:
food[1]

'Samosa'

In [16]:
food[0:]

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [17]:
price.mean()

5.0

In [18]:
# zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
# array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
# empty array
np.empty(5)

#1 someone think that empty function of an array provide empty array but its not quiet right
#2 actually when you use empty function it actually fills the array with arbitrary values(garbage) 
#but not random
#3 when you gave shape of 5 then its mean its create an 1_dimensional array with the elements of 5

# now if you want to create two dimensional array in this context then you should write below code
np.empty(shape =[5,2])

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.33512376e-306],
       [6.23059386e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11261027e-306],
       [2.22523140e-306, 1.02360867e-306]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# specify above range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [28]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [35]:
# line space
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [36]:
# specify your datatype
np.ones(5, dtype= np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [37]:
# specify your datatype
np.ones(5, dtype= np.float64)

array([1., 1., 1., 1., 1.])

# Array functions

In [38]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [39]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [40]:
b= np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [42]:
c= np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [45]:
c.sort
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# Two-Dimensional Arrays

In [50]:
x = np.array([[1,2],[5,4]])
x

array([[1, 2],
       [5, 4]])

In [51]:
y = np.array([[6,7],[7,8]])
y

array([[6, 7],
       [7, 8]])

In [52]:
c= np.concatenate((x,y), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [53]:
c= np.concatenate((x,y), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [57]:
a = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [58]:
# to find the number of dimensions
a.ndim
# its mean this array is three dimensional

3

In [59]:
b = np.array([[5,6,7],[8,9,10],[10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [60]:
b.ndim   # so this is two dimesnional array

2

In [61]:
# size of array mean number of elements in the array
a.size

24

In [63]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [62]:
a.shape
# shape tells us that this array has three dimensions and two rows with four columns

(3, 2, 4)

In [69]:
a = np.arange(9)    #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
# reshape 
a = a.reshape(3,3)  #3*3=9
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
# reshape
np.reshape(b, newshape=(1,9), order="C")

array([[ 5,  6,  7,  8,  9, 10, 10, 11, 12]])

In [74]:
# conver 1-D into 2-d
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a.shape

(9,)

In [76]:
# row vise 2_dimensional
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [77]:
b.shape

(1, 9)

In [78]:
# Column vise 2-dimensional

b = a[:, np.newaxis]
b


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [79]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [83]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
# multiply all elements of array with 6
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [84]:
# To get sum of array
a.sum()

45

In [85]:
# to find mean of array
a.mean()

5.0

In [ ]:
# numpy.org ->userGuide->absolute beginner
# u can practice from here